// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfN4U7LTl4kCPI7jsr6RVd1oXcyn1p1kU',
    appId: '1:987940245983:web:2400b39ade4abb9f86f46a',
    messagingSenderId: '987940245983',
    projectId: 'dupepro-1fef5',
    authDomain: 'dupepro-1fef5.firebaseapp.com',
    storageBucket: 'dupepro-1fef5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVOzL1PZ6A_Qe36culUv-4sXCt5wqX9U',
    appId: '1:987940245983:android:a5372b338cb87b2186f46a',
    messagingSenderId: '987940245983',
    projectId: 'dupepro-1fef5',
    storageBucket: 'dupepro-1fef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFUwStIThce1bKD3QZqwqQBzqqsvj2tio',
    appId: '1:987940245983:ios:d98259c556a3ac4786f46a',
    messagingSenderId: '987940245983',
    projectId: 'dupepro-1fef5',
    storageBucket: 'dupepro-1fef5.firebasestorage.app',
    iosBundleId: 'com.dupe.dupepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFUwStIThce1bKD3QZqwqQBzqqsvj2tio',
    appId: '1:987940245983:ios:d98259c556a3ac4786f46a',
    messagingSenderId: '987940245983',
    projectId: 'dupepro-1fef5',
    storageBucket: 'dupepro-1fef5.firebasestorage.app',
    iosBundleId: 'com.dupe.dupepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfN4U7LTl4kCPI7jsr6RVd1oXcyn1p1kU',
    appId: '1:987940245983:web:21bf3bf9f162ec0486f46a',
    messagingSenderId: '987940245983',
    projectId: 'dupepro-1fef5',
    authDomain: 'dupepro-1fef5.firebaseapp.com',
    storageBucket: 'dupepro-1fef5.firebasestorage.app',
  );
}
